package nostra.movie.java.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "FAVORITE")
public class Favorite {
    @Id
    @GeneratedValue
    @ApiModelProperty(value = "Autogenerated idFavorite")
    private int idFavorite;

    private String nameMovies;

//    @OneToMany(cascade = CascadeType.PERSIST)
//    @JoinColumn(name = "idFavoriteUser")
//    private List<User> user = new ArrayList<>();

//    @OneToMany(mappedBy = "favorite", cascade = CascadeType.PERSIST)
//    @JoinColumn(name = "idFavoriteMovie")
//    private List<Movies> movie = new ArrayList<>();

//    @ManyToOne(cascade = { CascadeType.PERSIST })
//    @JoinTable(name = "idFavoriteUser")
//    private User user;
//
//    @ManyToOne(cascade = CascadeType.PERSIST)
//    @JoinTable(name = "idFavoriteMovie")
//    private Movies movies;
}
