package nostra.movie.java.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "MOVIES")
@ApiModel(description = "All entity of Movies")
public class Movies {
    @Id
    @GeneratedValue
    @ApiModelProperty(value = "Autogenerated idMovies")
    private int idMovies;

    @ApiModelProperty(value = "This is nameMovies")
    private String nameMovies;

    @ApiModelProperty(value = "This is description")
    private String description;

    @ApiModelProperty(value = "This is rating")
    private double rating;

    @ApiModelProperty(value = "This is image")
    private String image;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @ApiModelProperty(value = "This is realseDate with format yyyy-MM-dd")
    private Date realseDate;

//    @ManyToOne(cascade = CascadeType.ALL)
//    @JoinColumn(name = "idFavoriteMovie")
//    private Favorite favorite;
//    @OneToMany(mappedBy = "favoriteMovie",cascade = CascadeType.ALL)
//    private List<Favorite> favorite = new ArrayList<>();

//    @ManyToOne
//    @JoinColumn(name = "idMovies")
//    private Movies movies;

    public Movies(String nameMovies, String description, double rating, String image, Date realseDate) {
        this.nameMovies = nameMovies;
        this.description = description;
        this.rating = rating;
        this.image = image;
        this.realseDate = realseDate;
    }
}
