package nostra.movie.java.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "RECOMENDATION")
@ApiModel(description = "All entity of Recomendation")
public class Recomendation {
    @Id
    @GeneratedValue
    @ApiModelProperty(value = "Autogenerated idRecomendation")
    private int idRecomendation;

    @ApiModelProperty(value = "This is category")
    private String category;

    @ApiModelProperty(value = "This is relationship tabel recomendation with movie")
    @ManyToOne
    @JoinColumn(name = "idMovies")
    private Movies movies;

}
