package nostra.movie.java.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "USERS")
@ApiModel(description = "All entity of User")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Autogenerated idUser")
    private int idUser;

    @ApiModelProperty(value = "This is name")
    private String name;

    @ApiModelProperty(value = "This is email")
    private String email;

    @ApiModelProperty(value = "This is phone")
    private String phone;

//    @OneToMany(mappedBy = "favorite",cascade = CascadeType.ALL)
//    private List<Favorite> favorite = new ArrayList<>();

    public User(String name, String email, String phone) {
        this.name = name;
        this.email = email;
        this.phone = phone;
    }
}
